---
title: "iteration_listcols"
output: html_document
date: "2023-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

## Lists 

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l
```

## accessing lists 

```{r}
l$vec_numeric
```

```{r}
l[[1]]
```

```{r}
l[[1]][1:3]
```

## for loops 

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(list_norms[[1]])
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## map 

```{r}
output = map(list_norms, mean_and_sd)
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(list_norms[[i]])
}

output = map(list_norms, median)
```

## map variants 

```{r}
output = map_dbl(list_norms, median, .id = "input")
```

```{r}
output = map_dfr(list_norms, mean_and_sd, .id = "input")
```

## listcols 

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

#select(name, mean_sd)
#mutate
```

```{r}
listcol_df |> pull(name)
```

```{r}
listcol_df |> pull(samp)
```

```{r}
listcol_df$samp[[1]]
```

```{r}
mean_and_sd(listcol_df$samp[[1]])
```

```{r}
map(listcol_df$samp, mean_and_sd)
```

#NSDUH

```{r}
nsduh_table <- function(html, table_num) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
}
```

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

output = vector("list", 3)

for (i in c(1, 4, 5)) {
  output[[i]] = nsduh_table(nsduh_html, i)
}

nsduh_results = bind_rows(output)
```

## again using maps 

```{r}
nsduh_df = 
  tibble(
    name = c("marj", "coke", "heroin"),
    number = c(1,4,5)
  )

#map(nsduh_df$number, nsduh_import, html = nsduh_html)

```

## operations on nested data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

```{r}
weather_nest = 
  nest(weather_df, data = date:tmin)

weather_nest
```

```{r}
weather_nest |> pull(name)
weather_nest |> pull(data)
```

## regressing tmax on tmin 

```{r}
#central_park_df = 
 # weather_nest |> 
 # filter(name == "CentralPark_NY") |> 
 # pull(df) |> 
  #nth(1)

#lm(tmax ~ tmin, data = central_park_df)
```

